name: Build and deploy Jekyll site
on:
 push:
   branches: ["feature/deploy"]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: actions/jekyll-build-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
      - name: Store SSH private key
        run: |
          pwd
          cat > ../ssh_key <<< $PRIVATE_KEY
        shell: bash
        env:
          PRIVATE_KEY : ${{secrets.SSH_PRIVATE_KEY}}
      - name: deploy over rsync
        run: |
          rsync \
            -e "ssh -o UserKnownHostsFile=.known_hosts" \
            --delete-after \
            -av \
            _site \
            remote@hosting:/directory
