name: Build and deploy Jekyll site
on:
 push:
   branches: ["master"]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: actions/jekyll-build-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
      - name: Add Cloudflare-specific config files
        run: sudo cp .cloudflare/* _site
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: a94ab6b361c4808bf8f6e263459c580d
          projectName: ar
          directory: _site
